config/routes.rb
Rails.application.routes.draw do
  get 'todopages/index'
  # get 'decdates/index'
  # get 'allplan/index'
  # get 'allplan/show'
  # post "/index/create" => "plan#create"
  get 'allplans/:id/users' , to:'allplans#user', as: :userid
  post 'allplans/:id/users' , to:'allplans#usercreate'
  get 'allplans/:id/users/:user_id/decdates' , to:'decdates#index', as: :decdateindex
  post 'allplans/:id/users/:user_id/decdates' , to:'decdates#create'
  get 'allplans/:id/sum' , to:'allplans#sum', as: :allplansum
  get 'allplans/:id/todopages' , to:'todopages#index', as: :todopage
  post 'allplans/:id/todopages' , to:'todopages#create'



  root 'allplans#index'
  resources :allplans do
    resources :days
    resources :todopages
    resources :users do
      resources :decdates , only: [:new, :show, :edit, :update, :destroy]
    end
  end

  # get 'plan/index'
  # post 'plan/new'
  # get 'plan/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/decdate.rb
class Decdate < ApplicationRecord
    belongs_to :allplan, foreign_key: 'allplan_id'
    belongs_to :user, foreign_key: 'user_id'

    validates :result, presence: true

end

app/controllers/decdates_controller.rb
class DecdatesController < ApplicationController
  def index
    @allplan = Allplan.find(params[:id])
    @playeatb = @allplan.playeat
    if @playeatb === "ご飯"
      @time = "18時以降"
    else
      @time = "一日空いている日"
    end
    @user = User.find(params[:user_id])
    @days = Day.where(allplan_id: @allplan.id).first(31)

    # @decdates = Decdate.all
    # @decdate = Decdate.new
    # @days = Day.all
    @form = Form::DecdateCollection.new
  end
  def create
    @form = Form::DecdateCollection.new(decdate_collection_params)
    if @form.save
      redirect_to todopage_path
    else
      flash[:alert] = 'Save error! '
      render :index
    end
  end
    # @decdates = Decdate.all
    # @days = Day.all
    # @days.each do |day|
    #   @decdate = @allplan.@user.decdate.new(decdate_params)
    # @decdate.save
    # end
    # redirect_to root_path
  def sum
    @allplan = Allplan.find(params[:id])

  end
  private

  def decdate_params
    params.require(:room).permit(:dectate_id, :user_id, :dateid, :result)
  end
  
  def decdate_collection_params
    params.require(:form_decdate_collection)
    .permit(decdates_attributes: [:allplan_id,:user_id, :dayid, :result])
  end
end

app/helpers/decdates_helper.rb
module DecdatesHelper
end

app/views/decdates/index.html.erb
<div>
  <div class="page5 text-center pt-150 ">
    <h2 class="pb-5 big"> 日程調整フォーム </h2>
    <h2 class="font-weight-bold pb-2 mb-3 middle"><%= "この予定は#{@playeatb}の予定です#{@time}の予定を入力してください" %></h2>
    
       <% j = 0 %>
       <%= form_with( model: [@allplan,@user,@form],url: decdateindex_path, method: :post) do |f| %>
         <%=  f.fields_for :decdates do |i| %>
           <%= i.hidden_field :allplan_id, :value => @allplan.id %>
           <%= i.hidden_field :user_id, :value => @user.id %>
           <%= i.hidden_field :dayid, :value => @days[j].id %>
          <p class="ml-2 middle"><%= "#{@days[j].month} #{@days[j].day}" %></p>
           <% j +=1 %>
        <p><%= i.label :result, '◎', value: 1 %></p>
        <p class="ml-1 mr-2"><%= i.radio_button :result, '1' %></p>
        <p><%= i.label :result, '✕', value: 0 %></p>
        <p class="ml-2"><%= i.radio_button :result, '0' %> </p><br>
      <% end %>
      <%= f.submit "送信",class: "px-3 py-1 mt-1 btn  btn-secondary font-weight-bold big"  %>
    <% end %>
  </div>
</div>