config/routes.rb
Rails.application.routes.draw do
  get 'todopages/index'
  # get 'decdates/index'
  # get 'allplan/index'
  # get 'allplan/show'
  # post "/index/create" => "plan#create"
  get 'allplans/:id/users' , to:'allplans#user', as: :userid
  post 'allplans/:id/users' , to:'allplans#usercreate'
  get 'allplans/:id/users/:user_id/decdates' , to:'decdates#index', as: :decdateindex
  post 'allplans/:id/users/:user_id/decdates' , to:'decdates#create'
  get 'allplans/:id/sum' , to:'allplans#sum', as: :allplansum
  get 'allplans/:id/todopages' , to:'todopages#index', as: :todopage
  post 'allplans/:id/todopages' , to:'todopages#create'



  root 'allplans#index'
  resources :allplans do
    resources :days
    resources :todopages
    resources :users do
      resources :decdates , only: [:new, :show, :edit, :update, :destroy]
    end
  end

  # get 'plan/index'
  # post 'plan/new'
  # get 'plan/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allplan.rb
class Allplan < ApplicationRecord
  has_many :days
  has_many :users
  has_many :decdates
  has_many :todopages
  has_many :result_todos
 
end

# 外部を入れるカラムを創る

app/controllers/allplans_controller.rb
class AllplansController < ApplicationController
  def index
    @allplans = Allplan.all
    @allplan = Allplan.new
  end
  def create
    @allplans = Allplan.all
    @allplan = Allplan.new(allplan_params)
    if @allplan.save
      redirect_to edit_allplan_path(@allplan)
    else
      render :index
    end
  end
  
  
  def user
    @allplan = Allplan.find(params[:id])
    @allplanid = Allplan.where(id: @allplan.id)
    @allplandedlind = @allplanid[0].created_at + (240 * 60 * 24)
    @allplannow = Time.now
    @flag = 0
    if @allplannow > @allplandedlind
      @flag = 1
    else
      @user = User.new
    end
    
    
  end
  def usercreate
    @allplan = Allplan.find(params[:id])
    @user = @allplan.users.new(user_params)
    if @user.save
      session[:current_user_id] = user.id
      @user = User.last
      redirect_to decdateindex_path(user_id: @user)
    else
      flash[:alert] = 'Save error! 名前が重複している可能性があります別の表記をお試しください'
      render :user
    end
    
  end
  
  def edit
    @allplan = Allplan.find(params[:id])
  end
  def update
    @allplan = Allplan.find(params[:id])
    @allplan.update(allplan_params)
    
    # ////////////////////////////////////////
    require "date"
    d = Date.today
    month = d.month
    date = d.day+3
    num = 0

    p month
    p date
    if month === 2 or month === 4 or month === 6 or month === 9
       while num < 31 do
        if date >= 30
          date = date -30;
          month += 1
        end
         date += 1
        #  monthbox.push(month)
        #  daybox.push(date)
        @allplan.days.create(month:month,day:date)
        num+=1
       end
    else
      while num < 31 do
        if  date >= 31
          date = date -31;
          month += 1
        end
         date = date += 1
        #  monthbox.push(month)
        #  daybox.push(date)
        @allplan.days.create(month:month,day:date)
        num+=1
      end
    end
    # ////////////////////////////////////////////

    redirect_to allplan_path(@allplan)
  end
  
  def show
    @allplan = Allplan.find(params[:id])
  end

  def sum
    @flag = 0
    @allplan = Allplan.find(params[:id])
    @allplanid = Allplan.where(id: @allplan.id)
    @allplandedlind = @allplanid[0].created_at + (240 * 60 * 24)
    @allplannow = Time.now
    lefttimes = @allplandedlind - @allplannow 
    lefttimemany =lefttimes / (60 * 60 * 24)
    @lefttime= lefttimemany.truncate(2)
    if @allplannow > @allplandedlind
      @flag = 1
      # 今の部屋のidを取得
      @allplan = Allplan.find(params[:id])
      # 今の部屋のユーザー全取得
      @users = User.where(allplan_id: @allplan.id)
      @usersleng = @users.length #3

      # 今の部屋の予定の結果全取得
      @decdates = Decdate.where(allplan_id: @allplan.id)
      @decdatesleng = @decdates.length  #93

      # 今の部屋の予定の結果全取得の中でdayidがi番目のもののdayidをdecdatedayidに入れる
      i = 0
      @sums = []
      while i < 31 do
        @decdatedayids = Decdate.where(dayid: @decdates[i].dayid)
        @decdatedayidsleng = @decdatedayids.length
        
        @sum = 0
        for decdatedayid in @decdatedayids do
          @sum = @sum+decdatedayid.result.to_i
        end
        @sums.push(@sum)
        i+=1
      end
      # 投票結果の中から最大値を求める
      @max_val= @sums.max
      # 最大値が何番目の要素か求める
      def search(target_num, sums)
        sums.each_with_index do |num, index|
          if num == target_num
            @max_point = index
          return
          end
        end
      end
      search(@max_val, @sums)
      #最大値番目のdayid取得
      @resultid = @decdates[@max_point].dayid
      # 日付idがわかったので、月と日にちを取り出す
      @resultdate = Day.find(@resultid)
      @resultmonth=@resultdate.month###################################
      @resultday=@resultdate.day######################################

      # 決まった日付idの日に丸のユーザーidを取得
      @resultuserids=[]
      @resultusers = Decdate.where(dayid: @resultid, result: 1)
      for resultuser in @resultusers do
        @resultuserids.push(resultuser.user_id)
      end
      # ユーザーidがわかったので、名前を取り出す 
      @resultusersid = User.where(id: @resultuserids)
      j = 0
      @resultusernames = []
      while j < @resultusersid.length do
      @resultusernames.push(@resultusersid[j].username)###################################
      j+=1
      end

      # やることを決める
      @todos = Todopage.where(allplan_id: @allplan.id)
      @todopoint = @todos.sample
      @todo = @allplan.result_todos.new(decdo: @todopoint.task)
      @todo.save
      @dectodo = ResultTodo.where(allplan_id: @allplan.id).first
    else
      @flag = 0
    end
    # @allplancreate = allplancreate.strftime("%Y年%m月%d日")

    # if test
      
    # end



  
  end
  private
  def allplan_params
     params.require(:allplan).permit(:dec_dateid,:dec_date,:playeat)
  end

  def user_params
     params.require(:user).permit(:username,:allplan_id)
  end

end

app/helpers/allplans_helper.rb
module AllplansHelper
end

app/views/allplans/edit.html.erb
<div>
  <div class="page2 text-center pt-150">
    <h2 class="font-weight-bold pb-5 big">イベントの内容を教えてください</h2>
      <%= form_with model: @allplan, local: true do |f| %>
        <h2><%= f.radio_button :playeat, :'遊び' %></h2>
        <h2 class="middle"><%= f.label :playeat, "遊び（一日の予定を集計します）", {value: :playeat} %></h2><br>
        <h2><%= f.radio_button :playeat, :'ご飯' %></h2>
        <h2 class="middle"><%= f.label :playeat, "ご飯（18時以降の予定を集計します)", {value: :playeat} %></h2><br>
        <%= f.submit "次へ",class: "px-3 py-2 btn  btn-secondary font-weight-bold" %>

      <% end %>

  </div>
</div>

app/views/allplans/index.html.erb
<div>
  <div>
    <div class="top text-center">
      <h1 class="font-weight-bold fontaizebig pt-3">smart adjust</h1>
      <div class = "toptext2">
        <%= form_with(model: @allplan, local: true) do |f| %>
        <%# ここの中身はいじらないで、（クラスはつけていいよ %>
          <%# <h4>Title</h4> %>
          <%= f.hidden_field :dec_dateid %>
        
          <%# <h4>Body</h4> %>
          <%= f.hidden_field :dec_date %>
        
          <%= f.hidden_field :playeat %>
        
          <%= f.submit 'イベントを作る', class: "p-3 btn  btn-secondary font-weight-bold"  %>
        <%# ここまで %>
        <% end %>
      </div>
    </div>
    <div>
      <h2 class="text-center py-5 font-weight-bold">あの面倒なイベント企画をいつでも！どこでも！だれとでも！"samrt"に"adjust"しよう！</h2>
    </div>
    <div class = "main redcolor text-center">
      <h2 class="text-white font-weight-bold p-4">今すぐ始められる簡単４ステップ</h2>
      <div class="flex">
        <!-- この下のDIVがflex -->
        <div class="col-sm-5 maincon bg-white min-height="400"">
          <div>
            <h3 class="Number">1</h3>
            <p class="title">遊びor夜ご飯で選択！</p>
            <%= image_tag '1.png', class:"img_preview" %>
            <p class="py-3">まず、ご飯を食べに行くかどこかへ遊びに行くかを選択します。</p>
          </div>
        </div>
        <div class="col-sm-5 maincon bg-white min-height="400"">
          <div>
            <h3 class="Number">2</h3>
            <p class="title">日程調整フォームに回答</p>
            <%= image_tag '2.png', class:"img_preview" %>
            <p class="py-3">1か月の日程が表示されますので、都合の良い日にちの選択を行います。</p>
          </div>
        </div>
        <div class="col-sm-5 maincon bg-white min-height="400"">
          <div>
            <h3 class="Number">3</h3>
            <p class="title">イベント詳細について案を回答</p>
            <%= image_tag '3.png', class:"img_preview" %>
            <p class="py-3">ご飯を食べに行くのであれば、どこに行きたいのか、遊びに行くのであればどこに行きたいのか、もしくは、何をしたいのかを投稿します。</p>
          </div>
        </div>
        <div class="col-sm-5 maincon bg-white min-height="400"">
          <div>
            <h3 class="Number4">4</h3>
            <p class="title">日程、すること、メンバー決定</p>
            <%= image_tag '4.png', class:"img_preview" %>
            <p class="py-3">全員が全ての作業を完了すれば、Smart Adjustがメンバー、日程そしてイベント内容を決定しお知らせします。</p>
          </div>
        </div>
      </div>
    </div>
    <div>
      <h2 class="text-center py-5 font-weight-bold">どんなに面倒なイベント企画もSmart Adjustにお任せください！</h2>
    </div>
    <div>
      <div class= "text-center redcolor pb-5">
        <h2 class=" py-5 font-weight-bold text-white">さっそく予定調整してみる</h2>
        <span>
          <%= form_with(model: @allplan, local: true) do |f| %>
            <%# ここの中身はいじらないで、（クラスはつけていいよ %>
            <%# <h4>Title</h4> %>
            <%= f.hidden_field :dec_dateid %>
        
            <%# <h4>Body</h4> %>
            <%= f.hidden_field :dec_date %>
        
            <%= f.hidden_field :playeat %>
        
            <span>
            <%= f.submit 'イベントを作る', class: "p-3 btn  btn-warning font-weight-bold"%>
            </spam>
             <%# ここまで %>
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/allplans/show.html.erb
<div>
  <div class="page3 text-center pt-150">
    <h2 class="font-weight-bold pb-3 big">日程調整URL（一か月分）</h2>
    <%= link_to "この文字を右クリック、スマホでは長押ししてコピーし、共有して下さい", userid_path,class: "small" %>
  </div>
</div>

app/views/allplans/sum.html.erb
<% if @flag === 1  %>
  <div>
    <div class="page7 text-center pt-150 ">
      <h5 class="big">集計が終わり、予定が決定しました!!!</h5>
      <p class=" mb-3 fonto28">以下のメンバーでグループを作成し、各自詳細を決定してください!!!</p>
      <div>
      <p class="middle d-block"><%= "日程:" %><span class=" middle font-weight-bold"><%= "2021年#{@resultmonth}月#{@resultday}日" %></span></p>
      <p class="middle">すること:<span class="font-weight-bold middle"><%= @dectodo.decdo %></span></p>
      <p class="middle d-block"><%= "メンバー" %></p>
      <span class="middle font-weight-bold"><% for @resultusername in @resultusernames do %></span>

        <p class="middle d-block"><span class="font-weight-bold"><%= @resultusername %></span></p><br> 
      <% end %>
    </div>
    <div class="middle todo pb-3 px-3 bordersolid pt-1">
      <p class="middle d-block">残りのTodo</p>
      <p class="middle d-block">・集合時間決定</p>
      <p class="middle d-block">・集合場所決定</p>
    </div>
  </div>
<% else %>

  <div>
    <div class="page6 text-center pt-150 ">
      <h3 class="font-weight-bold pb-2 big">結果の集計までしばらくお待ちください</h3>
      <%= "残り#{@lefttime}日です" %>
    </div>
  </div>
<% end %>

app/views/allplans/user.html.erb
<div>
  <div class="page4 text-center pt-150 ">
    <% if @flag === 1  %>
      <h2 class="font-weight-bold pb-2">投票期間が終了しました！</h2>
      <%= link_to '結果表示画面へ', allplansum_path %>
    <% else %>
    <h2 class="pb-4 big">日程調整フォーム</h2>
    <h2 class="font-weight-bold pb-2 middle">あなたの名前を教えてください</h2>
      <%= form_with(model: [@allplan,@user], local: true, class:"middle") do |f| %>
        <%= f.text_field :username %>
        <p>
          <%= f.submit '次へ',class: "px-3 py-1 mt-1 btn  btn-secondary font-weight-bold big" %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>